<a href="https://colab.research.google.com/github/Aggreygreg/pytorch-work/blob/main/PyTorch_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [165]:
import torch as t

In [166]:
my_torch = t.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [167]:
# Using reshape and view to manipulate
my_torch = my_torch.reshape(2,5)
my_torch

#reshape - number of items are divisible
#by the dimensions given(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [168]:
#reshape if we don't know the mumber of items
#using -1
my_torch2 = t.arange(10)
my_torch2 = my_torch2.reshape(2, -1)
my_torch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [169]:
# using view
my_torch3 = t.arange(10)
my_torch3


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [170]:
my_torch4 = my_torch3.view(2,5)
my_torch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [171]:
# with reshape and view, they will update
my_torch5 = t.arange(10)
my_torch5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [172]:
my_torch6 = my_torch5.reshape(2, 5)
my_torch6

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [173]:
my_torch5[1] = 4141
my_torch5

tensor([   0, 4141,    2,    3,    4,    5,    6,    7,    8,    9])

In [174]:
my_torch6

tensor([[   0, 4141,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [175]:
#using slices-grab a section of a tensor
my_torch7 = t.arange(10)
my_torch7[7] #grabbed specific item

tensor(7)

In [176]:
my_tensor8 = my_torch7.reshape(5,2)
my_tensor8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [177]:
my_tensor8[:, 0] #grabbed a slice

tensor([0, 2, 4, 6, 8])

In [178]:
my_tensor8[:, 1:]
#maintains the struct of the tensor

tensor([[1],
        [3],
        [5],
        [7],
        [9]])

In [179]:
# BASIC TENSOR MTH OPERATIONS
import numpy as n

In [180]:
tensor_a = t.tensor([1,2,3,4])
tensor_b = t.tensor([5,6,7,8])

In [181]:
#Addition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [182]:
#Addition long hand
t.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [183]:
#Subtraction
tensor_a - tensor_b

tensor([-4, -4, -4, -4])

In [184]:
#Subtraction long hand/ sub funtion
t.sub(tensor_a, tensor_b)

tensor([-4, -4, -4, -4])

In [185]:
#Multiplication
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [186]:
#Mult long hand
t.mul(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

In [187]:
#Division
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [188]:
#Div LH
t.div(tensor_b, tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [189]:
#Remainder (Modulus oprtn %)
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [190]:
#Remainder LH
t.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [191]:
#Exponents / Power
t.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

In [192]:
#Another Add LH
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

In [193]:
#Reassignment _
# tensor_a = tensor_a + tensor_b --- tensor_a outputs: tensor([ 6,  8, 10, 12])
tensor_a.add_(tensor_b)
tensor_a

tensor([ 6,  8, 10, 12])